########## DOCKER FILE COMPONENTS & DIFF COMMAND ###########

---> login to aws account and start your ec2 instance access it from putty or mobaxterm or git bash
---> now we have to create container fro,our own image
therefore, create one container first
--->docker run -it --name saddam ubuntu /bin/bash
--->cd /tmp
--->now create the file inside this tmp directory
---> touch myfile
--->now if you want to see the difference between the base image & changes on it then
--->docker diff saddam updateimage
o/p--> C /root
       A /root/.bash_history
       C /tmp
       A /tmp/myfile
[A=append or addition
 C=change
 D=deletion]
--->now create image of this container
--->docker commit newcontainer updateimage
container name=newcontainer
name of image=updateimage
--->docker images
now create container from this image
--->docker run -it --name sameer updateimage /bin/bash
[root@cid]# ls
[root@cid]# cd /tmp
[root@cid]# ls
o/p-->myfile {you will get all files back}

######## Dockerfile ########
---> Docker file is basically a test file it contains same set of instruction
---> automation of Docker image creation
######## DOCKER COMPONENTS #########
###### FROM
---> for the image this command must be top of the Dockerfile
###### RUN
---> To execute command's it will create a layer in image
###### MAINTAINER
---> author/owner/description
###### COPY
---> copy files fron local system (docker VM) we need to provide source, destination...
(we can't download file from internet and remote repo)
###### ADD
---> simmilar to copy but, it provides a feature to download files from internet, also we extract file at Docker image side..
###### EXPOSE
---> To execute port's such as port 8080 for tomcat, for port 80 for nginx
###### WORKDIR
---> to set working directory for a container
###### CMD
---> execute commands but during container creation
###### ENTRYPOINT
---> simmilar to cmd, but has higher priority over CMD, first commands will be executed. by ENTRYPOINT only....
###### ENV
---> Environment Variables
###### ARG
--->

###### PRACTICAL DEMO ON DOCKERFILE

---> create a file named dockerfile
---> add instructions in Dockerfile
---> build Dockerfile to create image
---> RUN image to create image

vi DOCKERFILE

FROM ubuntu: xyz
RUN echo "any content" >/tmp/testfile

to create image out of DOCKERFILE
docker build -t myimage
docker ps -a
docker images

---> now create the container from the above image
docker run -it --name containername imagename /bin/bash
cat /tmp/testfile

---> vi DOCKERFILE

FROM mysql: 5.7
WORKDIR /tmp
RUN echo "messege" > /tmp/testfile
COPY testfile/tmp
ADD test.tar.gz /tmp
